INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (1, 'бисау', '', 'https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg', 'вторая половинка страны Гвинеи-...', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (2, 'гот', null, null, 'молодежный неформал', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (3, 'битва', null, null, 'синоним бой, сражение', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (4, 'иисус', null, null, 'имя Христоса', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (5, 'слеза', null, null, 'глазное выделение', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (6, 'автор', null, null, 'Изготовитель собственного произведения', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (7, 'устюг', 'https://bringsluck.ru/music/Sergey Melnikov — Vspomni oseny.mp3', null, 'город Деда Мороза', 'audio');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (8, 'тапочки', null, null, 'домашняя обувь', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (9, 'миньоны', null, 'https://poncy.ru/media/uploads/dict/sln/m/i/minony.jpg', 'Анимационный фильм, приквел и спин-офф серии мультфильмов «Гадкий я»', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (10, 'банкрот', null, null, 'Несостоятельный должник', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (11, 'разгром', null, null, 'победа с большим счетом', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (12, 'потемки', null, null, 'Мрак для блуждания', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (13, 'стимпанк', null, 'https://cs.pikabu.ru/post_img/2014/01/02/12/1388692190_582876257.jpg', 'жанр научной фантастики, моделирующий мир, который в совершенстве освоил технологию паровых машин', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (14, 'реквизит', null, null, 'совокупность предметов для театрального представления', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (15, 'пчела', null, null, 'Насекомое, служащее достойным примером трудолюбия и защиты результатов своего труда', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (16, 'чебурашка', null, null, 'Лучший друг крокодила', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (17, 'пятиборец', null, null, 'Спортсмен - многостаночник', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (18, 'топология', null, null, 'Наука о свойствах геометрических фигур', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (19, 'оно', null, 'https://vokrug.tv/pic/news/3/b/e/7/3be771396a0e6b0f8c11fe5d82e6eeed.jpg', 'Фильм про клоуна', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (20, 'египет', null, 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg', 'Страна с фараонами', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (21, 'евнух', null, null, 'скопец — слуга в гареме', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (22, 'уезд', null, null, 'Административно-территориальная единица в Российской империи', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (23, 'ахцу', null, null, 'хребет в южной части Западного Кавказа', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (24, 'секвойя', null, 'https://bumans.ru/images/%D0%A1%D0%B5%D0%BA%D0%B2%D0%BE%D0%B9%D1%8F-1.jpg', 'высочайшее хвойное дерево', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (25, 'идиот', null, null, 'роман Ф. Достоевского; опера Вайнберга', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (26, 'лемур', null, null, 'Священное животное на Мадагаскаре', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (27, 'клавдий', null, 'https://sun9-29.userapi.com/impf/c851536/v851536025/189560/WFSor1KiVO8.jpg?size=800x543&quality=96&sign=d437992fe166fdcb1dbe5ab8c1a8be7c&type=album', 'I, римский император (41—54 гг.)', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (28, 'гаи', null, null, 'прежнее название ГИБДД', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (29, 'шрифт', null, null, 'начертание букв', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (30, 'яга', null, null, 'баба-', 'text');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (31, 'етун', null, 'https://chakiris.club/uploads/posts/2022-02/1645054581_4-chakiris-club-p-yotun-bog-fentezi-oboi-5.jpg', 'в скандинавской мифологии — великан, возникший из довременного хаоса мировой бездны', 'image');
INSERT INTO public.question (id, answer, audio, image, question, type) VALUES (32, 'некроз', null, null, 'омертвление тканей', 'text');